# Generated by Django 5.1.3 on 2024-12-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("range", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("school_id", models.CharField(max_length=20, unique=True)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
            ],
        ),
    ]
