# Generated by Django 5.1.3 on 2024-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("team_members", models.IntegerField()),
                ("code", models.FileField(upload_to="uploads/")),
                ("score", models.FloatField(default=0.0)),
                ("comment", models.TextField(blank=True)),
            ],
        ),
    ]
