# Generated by Django 5.1.3 on 2024-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team_members",
            field=models.CharField(max_length=255),
        ),
    ]
