# Generated by Django 5.0.4 on 2024-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
