# Generated by Django 5.0.4 on 2024-11-25 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_code_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="code_filename",
        ),
    ]
