# Generated by Django 5.0.4 on 2024-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_project_zip_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="zip_content",
        ),
        migrations.AddField(
            model_name="project",
            name="zip_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
