# Generated by Django 5.1.3 on 2024-12-01 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_rename_comment_project_description_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="zip_name",
        ),
    ]
