# Generated by Django 5.1.3 on 2024-12-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_comment_text_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(default="No text provided", verbose_name="댓글 내용"),
        ),
    ]
