# Generated by Django 5.1.3 on 2024-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_alter_comment_author_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
