# Generated by Django 5.1.3 on 2024-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_alter_comment_author_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
