# Generated by Django 5.1.4 on 2024-12-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="password",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="profile/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(default="default_nickname", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="range",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
