# Generated by Django 5.1.3 on 2024-12-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
            ],
        ),
    ]
